# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/devel/projects/C++/src/sip/core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/devel/projects/C++/src/sip/core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/devel/projects/C++/src/sip/core/CMakeFiles /data/devel/projects/C++/src/sip/core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/devel/projects/C++/src/sip/core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestMessageBuffer

# Build rule for target.
TestMessageBuffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestMessageBuffer
.PHONY : TestMessageBuffer

# fast build rule for target.
TestMessageBuffer/fast:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/build
.PHONY : TestMessageBuffer/fast

#=============================================================================
# Target rules for targets named TestSocketServer

# Build rule for target.
TestSocketServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSocketServer
.PHONY : TestSocketServer

# fast build rule for target.
TestSocketServer/fast:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/build
.PHONY : TestSocketServer/fast

#=============================================================================
# Target rules for targets named UdpSend

# Build rule for target.
UdpSend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UdpSend
.PHONY : UdpSend

# fast build rule for target.
UdpSend/fast:
	$(MAKE) -f CMakeFiles/UdpSend.dir/build.make CMakeFiles/UdpSend.dir/build
.PHONY : UdpSend/fast

#=============================================================================
# Target rules for targets named TestSessionManager

# Build rule for target.
TestSessionManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSessionManager
.PHONY : TestSessionManager

# fast build rule for target.
TestSessionManager/fast:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/build
.PHONY : TestSessionManager/fast

#=============================================================================
# Target rules for targets named Core

# Build rule for target.
Core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Core
.PHONY : Core

# fast build rule for target.
Core/fast:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/build
.PHONY : Core/fast

#=============================================================================
# Target rules for targets named Media

# Build rule for target.
Media: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Media
.PHONY : Media

# fast build rule for target.
Media/fast:
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/build
.PHONY : Media/fast

#=============================================================================
# Target rules for targets named TestSipParsing

# Build rule for target.
TestSipParsing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSipParsing
.PHONY : TestSipParsing

# fast build rule for target.
TestSipParsing/fast:
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/build
.PHONY : TestSipParsing/fast

#=============================================================================
# Target rules for targets named TestMappedBuffers

# Build rule for target.
TestMappedBuffers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestMappedBuffers
.PHONY : TestMappedBuffers

# fast build rule for target.
TestMappedBuffers/fast:
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/build
.PHONY : TestMappedBuffers/fast

lib/json/jsoncpp.o: lib/json/jsoncpp.cpp.o

.PHONY : lib/json/jsoncpp.o

# target to build an object file
lib/json/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/lib/json/jsoncpp.cpp.o
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/lib/json/jsoncpp.cpp.o
.PHONY : lib/json/jsoncpp.cpp.o

lib/json/jsoncpp.i: lib/json/jsoncpp.cpp.i

.PHONY : lib/json/jsoncpp.i

# target to preprocess a source file
lib/json/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/lib/json/jsoncpp.cpp.i
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/lib/json/jsoncpp.cpp.i
.PHONY : lib/json/jsoncpp.cpp.i

lib/json/jsoncpp.s: lib/json/jsoncpp.cpp.s

.PHONY : lib/json/jsoncpp.s

# target to generate assembly for a file
lib/json/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/lib/json/jsoncpp.cpp.s
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/lib/json/jsoncpp.cpp.s
.PHONY : lib/json/jsoncpp.cpp.s

src/applications/core.o: src/applications/core.cpp.o

.PHONY : src/applications/core.o

# target to build an object file
src/applications/core.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/applications/core.cpp.o
.PHONY : src/applications/core.cpp.o

src/applications/core.i: src/applications/core.cpp.i

.PHONY : src/applications/core.i

# target to preprocess a source file
src/applications/core.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/applications/core.cpp.i
.PHONY : src/applications/core.cpp.i

src/applications/core.s: src/applications/core.cpp.s

.PHONY : src/applications/core.s

# target to generate assembly for a file
src/applications/core.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/applications/core.cpp.s
.PHONY : src/applications/core.cpp.s

src/applications/media.o: src/applications/media.cpp.o

.PHONY : src/applications/media.o

# target to build an object file
src/applications/media.cpp.o:
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/applications/media.cpp.o
.PHONY : src/applications/media.cpp.o

src/applications/media.i: src/applications/media.cpp.i

.PHONY : src/applications/media.i

# target to preprocess a source file
src/applications/media.cpp.i:
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/applications/media.cpp.i
.PHONY : src/applications/media.cpp.i

src/applications/media.s: src/applications/media.cpp.s

.PHONY : src/applications/media.s

# target to generate assembly for a file
src/applications/media.cpp.s:
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/applications/media.cpp.s
.PHONY : src/applications/media.cpp.s

src/components/control/ControlInterface.o: src/components/control/ControlInterface.cpp.o

.PHONY : src/components/control/ControlInterface.o

# target to build an object file
src/components/control/ControlInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/ControlInterface.cpp.o
.PHONY : src/components/control/ControlInterface.cpp.o

src/components/control/ControlInterface.i: src/components/control/ControlInterface.cpp.i

.PHONY : src/components/control/ControlInterface.i

# target to preprocess a source file
src/components/control/ControlInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/ControlInterface.cpp.i
.PHONY : src/components/control/ControlInterface.cpp.i

src/components/control/ControlInterface.s: src/components/control/ControlInterface.cpp.s

.PHONY : src/components/control/ControlInterface.s

# target to generate assembly for a file
src/components/control/ControlInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/ControlInterface.cpp.s
.PHONY : src/components/control/ControlInterface.cpp.s

src/components/control/notifications/Notification.o: src/components/control/notifications/Notification.cpp.o

.PHONY : src/components/control/notifications/Notification.o

# target to build an object file
src/components/control/notifications/Notification.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/notifications/Notification.cpp.o
.PHONY : src/components/control/notifications/Notification.cpp.o

src/components/control/notifications/Notification.i: src/components/control/notifications/Notification.cpp.i

.PHONY : src/components/control/notifications/Notification.i

# target to preprocess a source file
src/components/control/notifications/Notification.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/notifications/Notification.cpp.i
.PHONY : src/components/control/notifications/Notification.cpp.i

src/components/control/notifications/Notification.s: src/components/control/notifications/Notification.cpp.s

.PHONY : src/components/control/notifications/Notification.s

# target to generate assembly for a file
src/components/control/notifications/Notification.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/notifications/Notification.cpp.s
.PHONY : src/components/control/notifications/Notification.cpp.s

src/components/control/requests/Request.o: src/components/control/requests/Request.cpp.o

.PHONY : src/components/control/requests/Request.o

# target to build an object file
src/components/control/requests/Request.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/requests/Request.cpp.o
.PHONY : src/components/control/requests/Request.cpp.o

src/components/control/requests/Request.i: src/components/control/requests/Request.cpp.i

.PHONY : src/components/control/requests/Request.i

# target to preprocess a source file
src/components/control/requests/Request.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/requests/Request.cpp.i
.PHONY : src/components/control/requests/Request.cpp.i

src/components/control/requests/Request.s: src/components/control/requests/Request.cpp.s

.PHONY : src/components/control/requests/Request.s

# target to generate assembly for a file
src/components/control/requests/Request.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/control/requests/Request.cpp.s
.PHONY : src/components/control/requests/Request.cpp.s

src/components/media/MediaClientInterface.o: src/components/media/MediaClientInterface.cpp.o

.PHONY : src/components/media/MediaClientInterface.o

# target to build an object file
src/components/media/MediaClientInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaClientInterface.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaClientInterface.cpp.o
.PHONY : src/components/media/MediaClientInterface.cpp.o

src/components/media/MediaClientInterface.i: src/components/media/MediaClientInterface.cpp.i

.PHONY : src/components/media/MediaClientInterface.i

# target to preprocess a source file
src/components/media/MediaClientInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaClientInterface.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaClientInterface.cpp.i
.PHONY : src/components/media/MediaClientInterface.cpp.i

src/components/media/MediaClientInterface.s: src/components/media/MediaClientInterface.cpp.s

.PHONY : src/components/media/MediaClientInterface.s

# target to generate assembly for a file
src/components/media/MediaClientInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaClientInterface.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaClientInterface.cpp.s
.PHONY : src/components/media/MediaClientInterface.cpp.s

src/components/media/MediaProcessor.o: src/components/media/MediaProcessor.cpp.o

.PHONY : src/components/media/MediaProcessor.o

# target to build an object file
src/components/media/MediaProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaProcessor.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaProcessor.cpp.o
.PHONY : src/components/media/MediaProcessor.cpp.o

src/components/media/MediaProcessor.i: src/components/media/MediaProcessor.cpp.i

.PHONY : src/components/media/MediaProcessor.i

# target to preprocess a source file
src/components/media/MediaProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaProcessor.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaProcessor.cpp.i
.PHONY : src/components/media/MediaProcessor.cpp.i

src/components/media/MediaProcessor.s: src/components/media/MediaProcessor.cpp.s

.PHONY : src/components/media/MediaProcessor.s

# target to generate assembly for a file
src/components/media/MediaProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaProcessor.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaProcessor.cpp.s
.PHONY : src/components/media/MediaProcessor.cpp.s

src/components/media/MediaServerInterface.o: src/components/media/MediaServerInterface.cpp.o

.PHONY : src/components/media/MediaServerInterface.o

# target to build an object file
src/components/media/MediaServerInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaServerInterface.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaServerInterface.cpp.o
.PHONY : src/components/media/MediaServerInterface.cpp.o

src/components/media/MediaServerInterface.i: src/components/media/MediaServerInterface.cpp.i

.PHONY : src/components/media/MediaServerInterface.i

# target to preprocess a source file
src/components/media/MediaServerInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaServerInterface.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaServerInterface.cpp.i
.PHONY : src/components/media/MediaServerInterface.cpp.i

src/components/media/MediaServerInterface.s: src/components/media/MediaServerInterface.cpp.s

.PHONY : src/components/media/MediaServerInterface.s

# target to generate assembly for a file
src/components/media/MediaServerInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/MediaServerInterface.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/MediaServerInterface.cpp.s
.PHONY : src/components/media/MediaServerInterface.cpp.s

src/components/media/messages/MediaMessage.o: src/components/media/messages/MediaMessage.cpp.o

.PHONY : src/components/media/messages/MediaMessage.o

# target to build an object file
src/components/media/messages/MediaMessage.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/messages/MediaMessage.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/messages/MediaMessage.cpp.o
.PHONY : src/components/media/messages/MediaMessage.cpp.o

src/components/media/messages/MediaMessage.i: src/components/media/messages/MediaMessage.cpp.i

.PHONY : src/components/media/messages/MediaMessage.i

# target to preprocess a source file
src/components/media/messages/MediaMessage.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/messages/MediaMessage.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/messages/MediaMessage.cpp.i
.PHONY : src/components/media/messages/MediaMessage.cpp.i

src/components/media/messages/MediaMessage.s: src/components/media/messages/MediaMessage.cpp.s

.PHONY : src/components/media/messages/MediaMessage.s

# target to generate assembly for a file
src/components/media/messages/MediaMessage.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/messages/MediaMessage.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/messages/MediaMessage.cpp.s
.PHONY : src/components/media/messages/MediaMessage.cpp.s

src/components/media/resource/AllocatedResource.o: src/components/media/resource/AllocatedResource.cpp.o

.PHONY : src/components/media/resource/AllocatedResource.o

# target to build an object file
src/components/media/resource/AllocatedResource.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/AllocatedResource.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/AllocatedResource.cpp.o
.PHONY : src/components/media/resource/AllocatedResource.cpp.o

src/components/media/resource/AllocatedResource.i: src/components/media/resource/AllocatedResource.cpp.i

.PHONY : src/components/media/resource/AllocatedResource.i

# target to preprocess a source file
src/components/media/resource/AllocatedResource.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/AllocatedResource.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/AllocatedResource.cpp.i
.PHONY : src/components/media/resource/AllocatedResource.cpp.i

src/components/media/resource/AllocatedResource.s: src/components/media/resource/AllocatedResource.cpp.s

.PHONY : src/components/media/resource/AllocatedResource.s

# target to generate assembly for a file
src/components/media/resource/AllocatedResource.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/AllocatedResource.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/AllocatedResource.cpp.s
.PHONY : src/components/media/resource/AllocatedResource.cpp.s

src/components/media/resource/MediaResource.o: src/components/media/resource/MediaResource.cpp.o

.PHONY : src/components/media/resource/MediaResource.o

# target to build an object file
src/components/media/resource/MediaResource.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/MediaResource.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/MediaResource.cpp.o
.PHONY : src/components/media/resource/MediaResource.cpp.o

src/components/media/resource/MediaResource.i: src/components/media/resource/MediaResource.cpp.i

.PHONY : src/components/media/resource/MediaResource.i

# target to preprocess a source file
src/components/media/resource/MediaResource.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/MediaResource.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/MediaResource.cpp.i
.PHONY : src/components/media/resource/MediaResource.cpp.i

src/components/media/resource/MediaResource.s: src/components/media/resource/MediaResource.cpp.s

.PHONY : src/components/media/resource/MediaResource.s

# target to generate assembly for a file
src/components/media/resource/MediaResource.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/MediaResource.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/MediaResource.cpp.s
.PHONY : src/components/media/resource/MediaResource.cpp.s

src/components/media/resource/ResourceManager.o: src/components/media/resource/ResourceManager.cpp.o

.PHONY : src/components/media/resource/ResourceManager.o

# target to build an object file
src/components/media/resource/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/ResourceManager.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/ResourceManager.cpp.o
.PHONY : src/components/media/resource/ResourceManager.cpp.o

src/components/media/resource/ResourceManager.i: src/components/media/resource/ResourceManager.cpp.i

.PHONY : src/components/media/resource/ResourceManager.i

# target to preprocess a source file
src/components/media/resource/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/ResourceManager.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/ResourceManager.cpp.i
.PHONY : src/components/media/resource/ResourceManager.cpp.i

src/components/media/resource/ResourceManager.s: src/components/media/resource/ResourceManager.cpp.s

.PHONY : src/components/media/resource/ResourceManager.s

# target to generate assembly for a file
src/components/media/resource/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/media/resource/ResourceManager.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/media/resource/ResourceManager.cpp.s
.PHONY : src/components/media/resource/ResourceManager.cpp.s

src/components/sip/SdpReceivedOffer.o: src/components/sip/SdpReceivedOffer.cpp.o

.PHONY : src/components/sip/SdpReceivedOffer.o

# target to build an object file
src/components/sip/SdpReceivedOffer.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SdpReceivedOffer.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SdpReceivedOffer.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SdpReceivedOffer.cpp.o
.PHONY : src/components/sip/SdpReceivedOffer.cpp.o

src/components/sip/SdpReceivedOffer.i: src/components/sip/SdpReceivedOffer.cpp.i

.PHONY : src/components/sip/SdpReceivedOffer.i

# target to preprocess a source file
src/components/sip/SdpReceivedOffer.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SdpReceivedOffer.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SdpReceivedOffer.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SdpReceivedOffer.cpp.i
.PHONY : src/components/sip/SdpReceivedOffer.cpp.i

src/components/sip/SdpReceivedOffer.s: src/components/sip/SdpReceivedOffer.cpp.s

.PHONY : src/components/sip/SdpReceivedOffer.s

# target to generate assembly for a file
src/components/sip/SdpReceivedOffer.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SdpReceivedOffer.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SdpReceivedOffer.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SdpReceivedOffer.cpp.s
.PHONY : src/components/sip/SdpReceivedOffer.cpp.s

src/components/sip/Session.o: src/components/sip/Session.cpp.o

.PHONY : src/components/sip/Session.o

# target to build an object file
src/components/sip/Session.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/Session.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/Session.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/Session.cpp.o
.PHONY : src/components/sip/Session.cpp.o

src/components/sip/Session.i: src/components/sip/Session.cpp.i

.PHONY : src/components/sip/Session.i

# target to preprocess a source file
src/components/sip/Session.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/Session.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/Session.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/Session.cpp.i
.PHONY : src/components/sip/Session.cpp.i

src/components/sip/Session.s: src/components/sip/Session.cpp.s

.PHONY : src/components/sip/Session.s

# target to generate assembly for a file
src/components/sip/Session.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/Session.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/Session.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/Session.cpp.s
.PHONY : src/components/sip/Session.cpp.s

src/components/sip/SessionManager.o: src/components/sip/SessionManager.cpp.o

.PHONY : src/components/sip/SessionManager.o

# target to build an object file
src/components/sip/SessionManager.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SessionManager.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SessionManager.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SessionManager.cpp.o
.PHONY : src/components/sip/SessionManager.cpp.o

src/components/sip/SessionManager.i: src/components/sip/SessionManager.cpp.i

.PHONY : src/components/sip/SessionManager.i

# target to preprocess a source file
src/components/sip/SessionManager.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SessionManager.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SessionManager.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SessionManager.cpp.i
.PHONY : src/components/sip/SessionManager.cpp.i

src/components/sip/SessionManager.s: src/components/sip/SessionManager.cpp.s

.PHONY : src/components/sip/SessionManager.s

# target to generate assembly for a file
src/components/sip/SessionManager.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SessionManager.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SessionManager.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SessionManager.cpp.s
.PHONY : src/components/sip/SessionManager.cpp.s

src/components/sip/SipConnection.o: src/components/sip/SipConnection.cpp.o

.PHONY : src/components/sip/SipConnection.o

# target to build an object file
src/components/sip/SipConnection.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipConnection.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipConnection.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipConnection.cpp.o
.PHONY : src/components/sip/SipConnection.cpp.o

src/components/sip/SipConnection.i: src/components/sip/SipConnection.cpp.i

.PHONY : src/components/sip/SipConnection.i

# target to preprocess a source file
src/components/sip/SipConnection.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipConnection.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipConnection.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipConnection.cpp.i
.PHONY : src/components/sip/SipConnection.cpp.i

src/components/sip/SipConnection.s: src/components/sip/SipConnection.cpp.s

.PHONY : src/components/sip/SipConnection.s

# target to generate assembly for a file
src/components/sip/SipConnection.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipConnection.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipConnection.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipConnection.cpp.s
.PHONY : src/components/sip/SipConnection.cpp.s

src/components/sip/SipInterface.o: src/components/sip/SipInterface.cpp.o

.PHONY : src/components/sip/SipInterface.o

# target to build an object file
src/components/sip/SipInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipInterface.cpp.o
.PHONY : src/components/sip/SipInterface.cpp.o

src/components/sip/SipInterface.i: src/components/sip/SipInterface.cpp.i

.PHONY : src/components/sip/SipInterface.i

# target to preprocess a source file
src/components/sip/SipInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipInterface.cpp.i
.PHONY : src/components/sip/SipInterface.cpp.i

src/components/sip/SipInterface.s: src/components/sip/SipInterface.cpp.s

.PHONY : src/components/sip/SipInterface.s

# target to generate assembly for a file
src/components/sip/SipInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipInterface.cpp.s
.PHONY : src/components/sip/SipInterface.cpp.s

src/components/sip/SipParser.o: src/components/sip/SipParser.cpp.o

.PHONY : src/components/sip/SipParser.o

# target to build an object file
src/components/sip/SipParser.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipParser.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipParser.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipParser.cpp.o
.PHONY : src/components/sip/SipParser.cpp.o

src/components/sip/SipParser.i: src/components/sip/SipParser.cpp.i

.PHONY : src/components/sip/SipParser.i

# target to preprocess a source file
src/components/sip/SipParser.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipParser.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipParser.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipParser.cpp.i
.PHONY : src/components/sip/SipParser.cpp.i

src/components/sip/SipParser.s: src/components/sip/SipParser.cpp.s

.PHONY : src/components/sip/SipParser.s

# target to generate assembly for a file
src/components/sip/SipParser.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/SipParser.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/SipParser.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/SipParser.cpp.s
.PHONY : src/components/sip/SipParser.cpp.s

src/components/sip/headers/SipHeader.o: src/components/sip/headers/SipHeader.cpp.o

.PHONY : src/components/sip/headers/SipHeader.o

# target to build an object file
src/components/sip/headers/SipHeader.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/headers/SipHeader.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/headers/SipHeader.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/headers/SipHeader.cpp.o
.PHONY : src/components/sip/headers/SipHeader.cpp.o

src/components/sip/headers/SipHeader.i: src/components/sip/headers/SipHeader.cpp.i

.PHONY : src/components/sip/headers/SipHeader.i

# target to preprocess a source file
src/components/sip/headers/SipHeader.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/headers/SipHeader.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/headers/SipHeader.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/headers/SipHeader.cpp.i
.PHONY : src/components/sip/headers/SipHeader.cpp.i

src/components/sip/headers/SipHeader.s: src/components/sip/headers/SipHeader.cpp.s

.PHONY : src/components/sip/headers/SipHeader.s

# target to generate assembly for a file
src/components/sip/headers/SipHeader.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/headers/SipHeader.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/headers/SipHeader.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/headers/SipHeader.cpp.s
.PHONY : src/components/sip/headers/SipHeader.cpp.s

src/components/sip/messages/SipInviteRequest.o: src/components/sip/messages/SipInviteRequest.cpp.o

.PHONY : src/components/sip/messages/SipInviteRequest.o

# target to build an object file
src/components/sip/messages/SipInviteRequest.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipInviteRequest.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipInviteRequest.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipInviteRequest.cpp.o
.PHONY : src/components/sip/messages/SipInviteRequest.cpp.o

src/components/sip/messages/SipInviteRequest.i: src/components/sip/messages/SipInviteRequest.cpp.i

.PHONY : src/components/sip/messages/SipInviteRequest.i

# target to preprocess a source file
src/components/sip/messages/SipInviteRequest.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipInviteRequest.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipInviteRequest.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipInviteRequest.cpp.i
.PHONY : src/components/sip/messages/SipInviteRequest.cpp.i

src/components/sip/messages/SipInviteRequest.s: src/components/sip/messages/SipInviteRequest.cpp.s

.PHONY : src/components/sip/messages/SipInviteRequest.s

# target to generate assembly for a file
src/components/sip/messages/SipInviteRequest.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipInviteRequest.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipInviteRequest.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipInviteRequest.cpp.s
.PHONY : src/components/sip/messages/SipInviteRequest.cpp.s

src/components/sip/messages/SipMessage.o: src/components/sip/messages/SipMessage.cpp.o

.PHONY : src/components/sip/messages/SipMessage.o

# target to build an object file
src/components/sip/messages/SipMessage.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipMessage.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipMessage.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipMessage.cpp.o
.PHONY : src/components/sip/messages/SipMessage.cpp.o

src/components/sip/messages/SipMessage.i: src/components/sip/messages/SipMessage.cpp.i

.PHONY : src/components/sip/messages/SipMessage.i

# target to preprocess a source file
src/components/sip/messages/SipMessage.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipMessage.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipMessage.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipMessage.cpp.i
.PHONY : src/components/sip/messages/SipMessage.cpp.i

src/components/sip/messages/SipMessage.s: src/components/sip/messages/SipMessage.cpp.s

.PHONY : src/components/sip/messages/SipMessage.s

# target to generate assembly for a file
src/components/sip/messages/SipMessage.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipMessage.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipMessage.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipMessage.cpp.s
.PHONY : src/components/sip/messages/SipMessage.cpp.s

src/components/sip/messages/SipRequest.o: src/components/sip/messages/SipRequest.cpp.o

.PHONY : src/components/sip/messages/SipRequest.o

# target to build an object file
src/components/sip/messages/SipRequest.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipRequest.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipRequest.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipRequest.cpp.o
.PHONY : src/components/sip/messages/SipRequest.cpp.o

src/components/sip/messages/SipRequest.i: src/components/sip/messages/SipRequest.cpp.i

.PHONY : src/components/sip/messages/SipRequest.i

# target to preprocess a source file
src/components/sip/messages/SipRequest.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipRequest.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipRequest.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipRequest.cpp.i
.PHONY : src/components/sip/messages/SipRequest.cpp.i

src/components/sip/messages/SipRequest.s: src/components/sip/messages/SipRequest.cpp.s

.PHONY : src/components/sip/messages/SipRequest.s

# target to generate assembly for a file
src/components/sip/messages/SipRequest.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/sip/messages/SipRequest.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/sip/messages/SipRequest.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/sip/messages/SipRequest.cpp.s
.PHONY : src/components/sip/messages/SipRequest.cpp.s

src/components/utilities/MessageBuffer.o: src/components/utilities/MessageBuffer.cpp.o

.PHONY : src/components/utilities/MessageBuffer.o

# target to build an object file
src/components/utilities/MessageBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/MessageBuffer.cpp.o
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/MessageBuffer.cpp.o
.PHONY : src/components/utilities/MessageBuffer.cpp.o

src/components/utilities/MessageBuffer.i: src/components/utilities/MessageBuffer.cpp.i

.PHONY : src/components/utilities/MessageBuffer.i

# target to preprocess a source file
src/components/utilities/MessageBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/MessageBuffer.cpp.i
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/MessageBuffer.cpp.i
.PHONY : src/components/utilities/MessageBuffer.cpp.i

src/components/utilities/MessageBuffer.s: src/components/utilities/MessageBuffer.cpp.s

.PHONY : src/components/utilities/MessageBuffer.s

# target to generate assembly for a file
src/components/utilities/MessageBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/MessageBuffer.cpp.s
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/MessageBuffer.cpp.s
.PHONY : src/components/utilities/MessageBuffer.cpp.s

src/components/utilities/SocketServer.o: src/components/utilities/SocketServer.cpp.o

.PHONY : src/components/utilities/SocketServer.o

# target to build an object file
src/components/utilities/SocketServer.cpp.o:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/SocketServer.cpp.o
.PHONY : src/components/utilities/SocketServer.cpp.o

src/components/utilities/SocketServer.i: src/components/utilities/SocketServer.cpp.i

.PHONY : src/components/utilities/SocketServer.i

# target to preprocess a source file
src/components/utilities/SocketServer.cpp.i:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/SocketServer.cpp.i
.PHONY : src/components/utilities/SocketServer.cpp.i

src/components/utilities/SocketServer.s: src/components/utilities/SocketServer.cpp.s

.PHONY : src/components/utilities/SocketServer.s

# target to generate assembly for a file
src/components/utilities/SocketServer.cpp.s:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/SocketServer.cpp.s
.PHONY : src/components/utilities/SocketServer.cpp.s

src/components/utilities/base64.o: src/components/utilities/base64.cpp.o

.PHONY : src/components/utilities/base64.o

# target to build an object file
src/components/utilities/base64.cpp.o:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/base64.cpp.o
.PHONY : src/components/utilities/base64.cpp.o

src/components/utilities/base64.i: src/components/utilities/base64.cpp.i

.PHONY : src/components/utilities/base64.i

# target to preprocess a source file
src/components/utilities/base64.cpp.i:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/base64.cpp.i
.PHONY : src/components/utilities/base64.cpp.i

src/components/utilities/base64.s: src/components/utilities/base64.cpp.s

.PHONY : src/components/utilities/base64.s

# target to generate assembly for a file
src/components/utilities/base64.cpp.s:
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/base64.cpp.s
.PHONY : src/components/utilities/base64.cpp.s

src/components/utilities/buffers.o: src/components/utilities/buffers.cpp.o

.PHONY : src/components/utilities/buffers.o

# target to build an object file
src/components/utilities/buffers.cpp.o:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/buffers.cpp.o
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/buffers.cpp.o
.PHONY : src/components/utilities/buffers.cpp.o

src/components/utilities/buffers.i: src/components/utilities/buffers.cpp.i

.PHONY : src/components/utilities/buffers.i

# target to preprocess a source file
src/components/utilities/buffers.cpp.i:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/buffers.cpp.i
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/buffers.cpp.i
.PHONY : src/components/utilities/buffers.cpp.i

src/components/utilities/buffers.s: src/components/utilities/buffers.cpp.s

.PHONY : src/components/utilities/buffers.s

# target to generate assembly for a file
src/components/utilities/buffers.cpp.s:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/src/components/utilities/buffers.cpp.s
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/src/components/utilities/buffers.cpp.s
.PHONY : src/components/utilities/buffers.cpp.s

tests/TestMappedBuffers.o: tests/TestMappedBuffers.cpp.o

.PHONY : tests/TestMappedBuffers.o

# target to build an object file
tests/TestMappedBuffers.cpp.o:
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tests/TestMappedBuffers.cpp.o
.PHONY : tests/TestMappedBuffers.cpp.o

tests/TestMappedBuffers.i: tests/TestMappedBuffers.cpp.i

.PHONY : tests/TestMappedBuffers.i

# target to preprocess a source file
tests/TestMappedBuffers.cpp.i:
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tests/TestMappedBuffers.cpp.i
.PHONY : tests/TestMappedBuffers.cpp.i

tests/TestMappedBuffers.s: tests/TestMappedBuffers.cpp.s

.PHONY : tests/TestMappedBuffers.s

# target to generate assembly for a file
tests/TestMappedBuffers.cpp.s:
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tests/TestMappedBuffers.cpp.s
.PHONY : tests/TestMappedBuffers.cpp.s

tests/TestMessageBuffer.o: tests/TestMessageBuffer.cpp.o

.PHONY : tests/TestMessageBuffer.o

# target to build an object file
tests/TestMessageBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tests/TestMessageBuffer.cpp.o
.PHONY : tests/TestMessageBuffer.cpp.o

tests/TestMessageBuffer.i: tests/TestMessageBuffer.cpp.i

.PHONY : tests/TestMessageBuffer.i

# target to preprocess a source file
tests/TestMessageBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tests/TestMessageBuffer.cpp.i
.PHONY : tests/TestMessageBuffer.cpp.i

tests/TestMessageBuffer.s: tests/TestMessageBuffer.cpp.s

.PHONY : tests/TestMessageBuffer.s

# target to generate assembly for a file
tests/TestMessageBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tests/TestMessageBuffer.cpp.s
.PHONY : tests/TestMessageBuffer.cpp.s

tests/TestSessionManager.o: tests/TestSessionManager.cpp.o

.PHONY : tests/TestSessionManager.o

# target to build an object file
tests/TestSessionManager.cpp.o:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tests/TestSessionManager.cpp.o
.PHONY : tests/TestSessionManager.cpp.o

tests/TestSessionManager.i: tests/TestSessionManager.cpp.i

.PHONY : tests/TestSessionManager.i

# target to preprocess a source file
tests/TestSessionManager.cpp.i:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tests/TestSessionManager.cpp.i
.PHONY : tests/TestSessionManager.cpp.i

tests/TestSessionManager.s: tests/TestSessionManager.cpp.s

.PHONY : tests/TestSessionManager.s

# target to generate assembly for a file
tests/TestSessionManager.cpp.s:
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tests/TestSessionManager.cpp.s
.PHONY : tests/TestSessionManager.cpp.s

tests/TestSipParsing.o: tests/TestSipParsing.cpp.o

.PHONY : tests/TestSipParsing.o

# target to build an object file
tests/TestSipParsing.cpp.o:
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tests/TestSipParsing.cpp.o
.PHONY : tests/TestSipParsing.cpp.o

tests/TestSipParsing.i: tests/TestSipParsing.cpp.i

.PHONY : tests/TestSipParsing.i

# target to preprocess a source file
tests/TestSipParsing.cpp.i:
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tests/TestSipParsing.cpp.i
.PHONY : tests/TestSipParsing.cpp.i

tests/TestSipParsing.s: tests/TestSipParsing.cpp.s

.PHONY : tests/TestSipParsing.s

# target to generate assembly for a file
tests/TestSipParsing.cpp.s:
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tests/TestSipParsing.cpp.s
.PHONY : tests/TestSipParsing.cpp.s

tests/TestSocketServer.o: tests/TestSocketServer.cpp.o

.PHONY : tests/TestSocketServer.o

# target to build an object file
tests/TestSocketServer.cpp.o:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tests/TestSocketServer.cpp.o
.PHONY : tests/TestSocketServer.cpp.o

tests/TestSocketServer.i: tests/TestSocketServer.cpp.i

.PHONY : tests/TestSocketServer.i

# target to preprocess a source file
tests/TestSocketServer.cpp.i:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tests/TestSocketServer.cpp.i
.PHONY : tests/TestSocketServer.cpp.i

tests/TestSocketServer.s: tests/TestSocketServer.cpp.s

.PHONY : tests/TestSocketServer.s

# target to generate assembly for a file
tests/TestSocketServer.cpp.s:
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tests/TestSocketServer.cpp.s
.PHONY : tests/TestSocketServer.cpp.s

tools/RaiiLog.o: tools/RaiiLog.cpp.o

.PHONY : tools/RaiiLog.o

# target to build an object file
tools/RaiiLog.cpp.o:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tools/RaiiLog.cpp.o
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tools/RaiiLog.cpp.o
.PHONY : tools/RaiiLog.cpp.o

tools/RaiiLog.i: tools/RaiiLog.cpp.i

.PHONY : tools/RaiiLog.i

# target to preprocess a source file
tools/RaiiLog.cpp.i:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tools/RaiiLog.cpp.i
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tools/RaiiLog.cpp.i
.PHONY : tools/RaiiLog.cpp.i

tools/RaiiLog.s: tools/RaiiLog.cpp.s

.PHONY : tools/RaiiLog.s

# target to generate assembly for a file
tools/RaiiLog.cpp.s:
	$(MAKE) -f CMakeFiles/TestMessageBuffer.dir/build.make CMakeFiles/TestMessageBuffer.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/TestSocketServer.dir/build.make CMakeFiles/TestSocketServer.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/TestSessionManager.dir/build.make CMakeFiles/TestSessionManager.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/Core.dir/build.make CMakeFiles/Core.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/Media.dir/build.make CMakeFiles/Media.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/TestSipParsing.dir/build.make CMakeFiles/TestSipParsing.dir/tools/RaiiLog.cpp.s
	$(MAKE) -f CMakeFiles/TestMappedBuffers.dir/build.make CMakeFiles/TestMappedBuffers.dir/tools/RaiiLog.cpp.s
.PHONY : tools/RaiiLog.cpp.s

tools/UdpSend.o: tools/UdpSend.cpp.o

.PHONY : tools/UdpSend.o

# target to build an object file
tools/UdpSend.cpp.o:
	$(MAKE) -f CMakeFiles/UdpSend.dir/build.make CMakeFiles/UdpSend.dir/tools/UdpSend.cpp.o
.PHONY : tools/UdpSend.cpp.o

tools/UdpSend.i: tools/UdpSend.cpp.i

.PHONY : tools/UdpSend.i

# target to preprocess a source file
tools/UdpSend.cpp.i:
	$(MAKE) -f CMakeFiles/UdpSend.dir/build.make CMakeFiles/UdpSend.dir/tools/UdpSend.cpp.i
.PHONY : tools/UdpSend.cpp.i

tools/UdpSend.s: tools/UdpSend.cpp.s

.PHONY : tools/UdpSend.s

# target to generate assembly for a file
tools/UdpSend.cpp.s:
	$(MAKE) -f CMakeFiles/UdpSend.dir/build.make CMakeFiles/UdpSend.dir/tools/UdpSend.cpp.s
.PHONY : tools/UdpSend.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... TestMessageBuffer"
	@echo "... TestSocketServer"
	@echo "... UdpSend"
	@echo "... TestSessionManager"
	@echo "... Core"
	@echo "... Media"
	@echo "... rebuild_cache"
	@echo "... TestSipParsing"
	@echo "... TestMappedBuffers"
	@echo "... lib/json/jsoncpp.o"
	@echo "... lib/json/jsoncpp.i"
	@echo "... lib/json/jsoncpp.s"
	@echo "... src/applications/core.o"
	@echo "... src/applications/core.i"
	@echo "... src/applications/core.s"
	@echo "... src/applications/media.o"
	@echo "... src/applications/media.i"
	@echo "... src/applications/media.s"
	@echo "... src/components/control/ControlInterface.o"
	@echo "... src/components/control/ControlInterface.i"
	@echo "... src/components/control/ControlInterface.s"
	@echo "... src/components/control/notifications/Notification.o"
	@echo "... src/components/control/notifications/Notification.i"
	@echo "... src/components/control/notifications/Notification.s"
	@echo "... src/components/control/requests/Request.o"
	@echo "... src/components/control/requests/Request.i"
	@echo "... src/components/control/requests/Request.s"
	@echo "... src/components/media/MediaClientInterface.o"
	@echo "... src/components/media/MediaClientInterface.i"
	@echo "... src/components/media/MediaClientInterface.s"
	@echo "... src/components/media/MediaProcessor.o"
	@echo "... src/components/media/MediaProcessor.i"
	@echo "... src/components/media/MediaProcessor.s"
	@echo "... src/components/media/MediaServerInterface.o"
	@echo "... src/components/media/MediaServerInterface.i"
	@echo "... src/components/media/MediaServerInterface.s"
	@echo "... src/components/media/messages/MediaMessage.o"
	@echo "... src/components/media/messages/MediaMessage.i"
	@echo "... src/components/media/messages/MediaMessage.s"
	@echo "... src/components/media/resource/AllocatedResource.o"
	@echo "... src/components/media/resource/AllocatedResource.i"
	@echo "... src/components/media/resource/AllocatedResource.s"
	@echo "... src/components/media/resource/MediaResource.o"
	@echo "... src/components/media/resource/MediaResource.i"
	@echo "... src/components/media/resource/MediaResource.s"
	@echo "... src/components/media/resource/ResourceManager.o"
	@echo "... src/components/media/resource/ResourceManager.i"
	@echo "... src/components/media/resource/ResourceManager.s"
	@echo "... src/components/sip/SdpReceivedOffer.o"
	@echo "... src/components/sip/SdpReceivedOffer.i"
	@echo "... src/components/sip/SdpReceivedOffer.s"
	@echo "... src/components/sip/Session.o"
	@echo "... src/components/sip/Session.i"
	@echo "... src/components/sip/Session.s"
	@echo "... src/components/sip/SessionManager.o"
	@echo "... src/components/sip/SessionManager.i"
	@echo "... src/components/sip/SessionManager.s"
	@echo "... src/components/sip/SipConnection.o"
	@echo "... src/components/sip/SipConnection.i"
	@echo "... src/components/sip/SipConnection.s"
	@echo "... src/components/sip/SipInterface.o"
	@echo "... src/components/sip/SipInterface.i"
	@echo "... src/components/sip/SipInterface.s"
	@echo "... src/components/sip/SipParser.o"
	@echo "... src/components/sip/SipParser.i"
	@echo "... src/components/sip/SipParser.s"
	@echo "... src/components/sip/headers/SipHeader.o"
	@echo "... src/components/sip/headers/SipHeader.i"
	@echo "... src/components/sip/headers/SipHeader.s"
	@echo "... src/components/sip/messages/SipInviteRequest.o"
	@echo "... src/components/sip/messages/SipInviteRequest.i"
	@echo "... src/components/sip/messages/SipInviteRequest.s"
	@echo "... src/components/sip/messages/SipMessage.o"
	@echo "... src/components/sip/messages/SipMessage.i"
	@echo "... src/components/sip/messages/SipMessage.s"
	@echo "... src/components/sip/messages/SipRequest.o"
	@echo "... src/components/sip/messages/SipRequest.i"
	@echo "... src/components/sip/messages/SipRequest.s"
	@echo "... src/components/utilities/MessageBuffer.o"
	@echo "... src/components/utilities/MessageBuffer.i"
	@echo "... src/components/utilities/MessageBuffer.s"
	@echo "... src/components/utilities/SocketServer.o"
	@echo "... src/components/utilities/SocketServer.i"
	@echo "... src/components/utilities/SocketServer.s"
	@echo "... src/components/utilities/base64.o"
	@echo "... src/components/utilities/base64.i"
	@echo "... src/components/utilities/base64.s"
	@echo "... src/components/utilities/buffers.o"
	@echo "... src/components/utilities/buffers.i"
	@echo "... src/components/utilities/buffers.s"
	@echo "... tests/TestMappedBuffers.o"
	@echo "... tests/TestMappedBuffers.i"
	@echo "... tests/TestMappedBuffers.s"
	@echo "... tests/TestMessageBuffer.o"
	@echo "... tests/TestMessageBuffer.i"
	@echo "... tests/TestMessageBuffer.s"
	@echo "... tests/TestSessionManager.o"
	@echo "... tests/TestSessionManager.i"
	@echo "... tests/TestSessionManager.s"
	@echo "... tests/TestSipParsing.o"
	@echo "... tests/TestSipParsing.i"
	@echo "... tests/TestSipParsing.s"
	@echo "... tests/TestSocketServer.o"
	@echo "... tests/TestSocketServer.i"
	@echo "... tests/TestSocketServer.s"
	@echo "... tools/RaiiLog.o"
	@echo "... tools/RaiiLog.i"
	@echo "... tools/RaiiLog.s"
	@echo "... tools/UdpSend.o"
	@echo "... tools/UdpSend.i"
	@echo "... tools/UdpSend.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

